version: '3.5'

services:
  db:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # DATABASE_USER
      MONGO_INITDB_ROOT_PASSWORD: admin # DATABASE_PASS
    volumes:
      - mongo-config:/data/configdb
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    container_name: api
    environment:
      DATABASE_NAME: scrape # DATABASE_NAME
      DATABASE_USER: admin # DATABASE_USER
      DATABASE_PASS: admin # DATABASE_PASS
      DATABASE_URI: mongodb://mongo:27017/scrape # DATABASE_URI, example: mongodb://database:27017
    ports:
      - '3000:3000'
    depends_on:
      - db

  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
      API_URL: http://backend:3000
    restart: always
    ports:
      - 3001:3000
    depends_on:
      - backend
