version: '3.5'

services:
  db:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # DATABASE_USER
      MONGO_INITDB_ROOT_PASSWORD: admin # DATABASE_PASS
    volumes:
      - ./mongo-config:/data/configdb
      - ./mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: api
    environment:
      DATABASE_NAME: scrape # DATABASE_NAME
      DATABASE_USER: admin # DATABASE_USER
      DATABASE_PASS: admin # DATABASE_PASS
      DATABASE_URI: mongodb://db:27017 # DATABASE_URI, example: mongodb://database:27017
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src

  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
      API_URL: http://backend:3000
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/public:/app/public
      - ./frontend/.env:/app/.env
    restart: always
    ports:
      - 3001:3000
    depends_on:
      - backend
