import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'APK Scraper - Home',
  description: 'Generated by FmB',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="bg-white">
            <div className="min-h-screen flex flex-row flex-nowrap items-start justify-start">
              <div
                id="sidebar"
                className="w-64 min-h-[900px] bg-[#f4f4f5] text-white flex flex-col items-center justify-between rounded-md mt-8 mx-8"
              ></div>
              <div id="wrapper" className="flex flex-col w-full">
                <div
                  id="navbar"
                  className="flex justify-between items-center h-16 px-8 bg-[#f4f4f5] text-white rounded-md mt-8 mr-8"
                ></div>
                {children}
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
